server:
  port: 1841

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genfu?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ssmdemo.model